<?php

namespace Inc\Api\Callbacks ;

class AddUploadCallback
{


public static function fileUpload($file, $override){


    if ( ! function_exists( 'wp_handle_upload' ) ) {
        require_once( ABSPATH . 'wp-admin/includes/file.php' );
    }
     
    $uploadedfile = $_FILES[$file];
     
    $upload_overrides = array(
        'test_form' => false
    );
     
    $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
     
    if ( $movefile && ! isset( $movefile['error'] ) ) {
        echo __( 'File is valid, and was successfully uploaded.', 'textdomain' ) . "\n";
        var_dump( $movefile );
    } else {
        /*
         * Error generated by _wp_handle_upload()
         * @see _wp_handle_upload() in wp-admin/includes/file.php
         */
        echo $movefile['error'];
    }
}

}
